# Generated by Django 5.0.3 on 2024-03-28 10:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="phone_number",
            field=models.IntegerField(unique=True),
        ),
    ]
