# Generated by Django 5.0.3 on 2024-03-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0002_remove_attendance_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="duration",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
